#!/bin/bash
DIR=`dirname $0`
GEN_INPUTFILE=$DIR/lib/generate_inputfile.sh
GEN_OUTPUTFILE=$DIR/lib/gitlog_date.py
GEN_CHARTS=$DIR/lib/visualize_commit.rscript
OUTPUTFILE=/tmp/viscommit.csv
R=/usr/bin/R
CHART_FILENAME=$1
USERNAME=$2

${GEN_INPUTFILE} | ${GEN_OUTPUTFILE} "${USERNAME}" ${OUTPUTFILE}
${R} -f ${GEN_CHARTS} --args ${CHART_FILENAME}
